//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserManagement.Exceptions.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha de confirmação deve ser informada..
        /// </summary>
        public static string CONFIRMACAO_SENHA_EM_BRANCO {
            get {
                return ResourceManager.GetString("CONFIRMACAO_SENHA_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de confirmação inválida. A senha de confirmação deve ter no minímo 8 caracteres, sendo, ao menos uma letra maiuscula, uma minuscula, um simbolo e um numero..
        /// </summary>
        public static string CONFIRMACAO_SENHA_FRACA {
            get {
                return ResourceManager.GetString("CONFIRMACAO_SENHA_FRACA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado já está registrado na base de dados..
        /// </summary>
        public static string EMAIL_JA_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_JA_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado não está registrado na base de dados. Por favor, utilize outro e-mail..
        /// </summary>
        public static string EMAIL_NAO_REGISTRADO {
            get {
                return ResourceManager.GetString("EMAIL_NAO_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário é invalido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo para verificação de e-mail expirado..
        /// </summary>
        public static string EMAIL_VERIFICACAO_EXPIRADO {
            get {
                return ResourceManager.GetString("EMAIL_VERIFICACAO_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel adicionar essa Claim..
        /// </summary>
        public static string ERRO_ADD_CLAIM_TO_USER {
            get {
                return ResourceManager.GetString("ERRO_ADD_CLAIM_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao adicionar role, tente novamente mais tarde..
        /// </summary>
        public static string ERRO_ADD_ROLE {
            get {
                return ResourceManager.GetString("ERRO_ADD_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário não foi adicionado a esta role..
        /// </summary>
        public static string ERRO_ADD_USER_TO_ROLE {
            get {
                return ResourceManager.GetString("ERRO_ADD_USER_TO_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na verificação..
        /// </summary>
        public static string FALHA_VERIFICACAO_EMAIL {
            get {
                return ResourceManager.GetString("FALHA_VERIFICACAO_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não possui permissão para acessar este recurso..
        /// </summary>
        public static string FORBIDEN {
            get {
                return ResourceManager.GetString("FORBIDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail e/ou senha estão incorretos..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do pet deve ser informado..
        /// </summary>
        public static string NOME_PET_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_PET_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário deve ser informado..
        /// </summary>
        public static string NOME_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O número deve ser informado..
        /// </summary>
        public static string NUMERO_ENDERECO_EM_BRANCO {
            get {
                return ResourceManager.GetString("NUMERO_ENDERECO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do usuário deve ser informado..
        /// </summary>
        public static string NUMERO_TELEFONE_EM_BRANCO {
            get {
                return ResourceManager.GetString("NUMERO_TELEFONE_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e a confirmação de senha devem ser iguais..
        /// </summary>
        public static string PASSWORD_AND_CONFIRMATION_ARE_DIFFERENT {
            get {
                return ResourceManager.GetString("PASSWORD_AND_CONFIRMATION_ARE_DIFFERENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa não é sua senha..
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo para redefinição de senha excedido..
        /// </summary>
        public static string PASSWORD_TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("PASSWORD_TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password token inválido..
        /// </summary>
        public static string PASSWORD_TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("PASSWORD_TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token não encontrado..
        /// </summary>
        public static string REFRESH_TOKEN_NOT_FOUND {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este token foi revogado..
        /// </summary>
        public static string REFRESH_TOKEN_REVOKED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_REVOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse RefreshToken já foi utilizado e não é mais válido..
        /// </summary>
        public static string REFRESH_TOKEN_USED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a role que deseja criar..
        /// </summary>
        public static string ROLE_EM_BRANCO {
            get {
                return ResourceManager.GetString("ROLE_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa role já existe..
        /// </summary>
        public static string ROLE_JA_EXISTE {
            get {
                return ResourceManager.GetString("ROLE_JA_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa role não existe..
        /// </summary>
        public static string ROLE_NAO_EXISTE {
            get {
                return ResourceManager.GetString("ROLE_NAO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida. A senha do usuário deve ter no minímo 8 caracteres, sendo, ao menos uma letra maiuscula, uma minuscula, um simbolo e um numero..
        /// </summary>
        public static string SENHA_FRACA {
            get {
                return ResourceManager.GetString("SENHA_FRACA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário deve ser informada..
        /// </summary>
        public static string SENHA_USUARIO_EM_BRANCO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_EM_BRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do usuário deve estar no formato XX X XXXX-XXXX ou XX X XXXX XXXX.
        /// </summary>
        public static string TELEFONE_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token do usuário expirou..
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este token é inválido..
        /// </summary>
        public static string TOKEN_INVALIDO {
            get {
                return ResourceManager.GetString("TOKEN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deve estar autenticado para ter acesso..
        /// </summary>
        public static string UNAUNTHORIZED {
            get {
                return ResourceManager.GetString("UNAUNTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha na verificação..
        /// </summary>
        public static string VALIDAR_REFRESH_TOKEN {
            get {
                return ResourceManager.GetString("VALIDAR_REFRESH_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, verifique seu e-mail..
        /// </summary>
        public static string VERIFICAR_EMAIL {
            get {
                return ResourceManager.GetString("VERIFICAR_EMAIL", resourceCulture);
            }
        }
    }
}
